// Code generated by "stringer -type=CausedBy"; DO NOT EDIT

package errors

import "fmt"

const _CausedBy_name = "ByBugByRuntimeByExternalByInputNoError"

var _CausedBy_index = [...]uint8{0, 5, 14, 24, 31, 38}

func (i CausedBy) String() string {
	if i < 0 || i >= CausedBy(len(_CausedBy_index)-1) {
		return fmt.Sprintf("CausedBy(%d)", i)
	}
	return _CausedBy_name[_CausedBy_index[i]:_CausedBy_index[i+1]]
}
